# 端口号
server:
  port: 8080
# 数据库连接
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://1.117.69.129:3306/tagster?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: Tagster
    driver-class-name: com.mysql.cj.jdbc.Driver

  #文件配置上传
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
file:
  upload:
    dir: "/Applications/code/java/tagster/files/uploadFiles/"

# mybatis配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.azhe.tagster.pojo.*

logging:
  level:
    com.azhe.tagster.mapper: debug







